### ISSUE TITLE
Linking MNIS data to TheyWorkForYou

### ISSUE THREAD

**Issue by jblumenau** [olihawkins/mnis#1]
Hi Oli,

I came across this whilst working on my R package for the TheyWorkForYou API ([twfyR](http://github.com/jblumenau/twfyR)) and was wondering whether your mnis package provides any common identifiers between MPs in the Members Names Information Service and MPs in TheyWorkForYou. I don't think I have seen anyone doing this, but my guess is that this would be a useful resource. I am considering investing some time to join up these data sources, but don't want to duplicate any pre-existing effort.

Any thoughts would be appreciated!

Thanks,

Jack

p.s. Probably should have emailed this, but it is tangentially related to this package! Hope you are well, btw.

**Comment by olihawkins** [comment]
Hi Jack,

Your package looks great! No, the mnis library doesn't provide any way of linking MNIS ids to TWFY ids and that would be a really useful resource to have.

The mnis library is fairly small and provides a way for us to answer the most common questions we get on MPs and their memberships of the House of Commons over time. But it could be expanded to support a much wider range of functionality. It's all a question of time and resources. Will hopefully find some time to do some more work on it soon.

Do let me know if you build any linking resources. Will keep an eye on your project too.

Hope you're well,

Oli

**Comment by jblumenau** [comment]
Thanks! Interesting. I have some resources to devote to this type of thing at the moment, so perhaps we should talk about this further if it is something that you and/or HoC people might be interested in. I'll send an email!

**Comment by olihawkins** [comment]
I'm going to close this as a potential feature for future development rather than something that needs fixing to deliver the currently intended functionality.
