### ISSUE TITLE
Handling file encoding

### ISSUE THREAD

**Issue by psychemedia** [olihawkins/mnis#2]
Rather than kludge the BOM encoding on the MNIS JSON, I think you can say:

    # Make request
    response = requests.get(url, headers=headers)
    response.encoding='utf-8-sig'

    # Parse JSON
    members = response.json()

**Comment by olihawkins** [comment]
Thanks Tony. Yes, that looks a bit more elegant! Will fix and upload soon.

**Comment by olihawkins** [comment]
Just took the pull request. Thanks mate.
